name: CICD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
           node-version: '16.20.1'  # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build artifact
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Authenticate with Netlify
        run: npx netlify login
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Deploy to Netlify
        run: npx npx netlify-cli deploy --prod --dir=build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Retrieve Deployed URL
        run: echo "::set-output name=deployed_url::$(npx netlify-cli deploy --json --prod --dir=build | jq -r '.deploy_url')"
        id: get-deploy-url
      - name: Send Deployment Notification Email
        run: |
          DEPLOYED_URL="${{ steps.deploy-output.outputs.deployed_url }}"
          # You can now use the $DEPLOYED_URL variable in your email content or send it wherever you need.
          echo "Your deployed app URL: ${DEPLOYED_URL}"
          # Add code here to send the email, for example using the `send_email.sh` script or another email service.
      